export const data = {
    labels: [
        'England',
        'Airedale NHS Foundation Trust',
        'Ashford and St Peter`s Hospitals NHS Foundation Trust',
        'Barking, Havering and Redbridge University Hospitals NHS Trust',
        'Barnsley Hospital NHS Foundation Trust',
        'Barts Health NHS Trust',
        'Basildon and Thurrock University Hospitals NHS Foundation Trust',
        'Bedford Hospital NHS Trust',
        'Bedfordshire Hospitals NHS Foundation Trust',
        'Blackpool Teaching Hospitals NHS Foundation Trust',
        'Bolton NHS Foundation Trust',
        'Bradford Teaching Hospitals NHS Foundation Trust',
        'Brighton and Sussex University Hospitals NHS Trust',
        'Buckinghamshire Healthcare NHS Trust',
        'Calderdale and Huddersfield NHS Foundation Trust',
        'Cambridge University Hospitals NHS Foundation Trust',
        'Chelsea and Westminster Hospital NHS Foundation Trust',
        'Chesterfield Royal Hospital NHS Foundation Trust',
        'Countess of Chester Hospital NHS Foundation Trust',
        'County Durham and Darlington NHS Foundation Trust',
        'Croydon Health Services NHS Trust',
        'Dartford and Gravesham NHS Trust',
        'Doncaster and Bassetlaw Teaching Hospitals NHS Foundation Trust',
        'Dorset County Hospital NHS Foundation Trust',
        'East and North Hertfordshire NHS Trust',
        'East Cheshire NHS Trust',
        'East Kent Hospitals University NHS Foundation Trust',
        'East Lancashire Hospitals NHS Trust',
        'East Suffolk and North Essex NHS Foundation Trust',
        'East Sussex Healthcare NHS Trust',
        'Epsom and St Helier University Hospitals NHS Trust',
        'Frimley Health NHS Foundation Trust',
        'Gateshead Health NHS Foundation Trust',
        'George Eliot Hospital NHS Trust',
        'Gloucestershire Hospitals NHS Foundation Trust',
        'Great Ormond Street Hospital For Children NHS Foundation Trust',
        'Great Western Hospitals NHS Foundation Trust',
        'Guy`s and St Thomas` NHS Foundation Trust',
        'Hampshire Hospitals NHS Foundation Trust',
        'Harrogate and District NHS Foundation Trust',
        'Homerton University Hospital NHS Foundation Trust',
        'Hull University Teaching Hospitals NHS Trust',
        'Imperial College Healthcare NHS Trust',
        'James Paget University Hospitals NHS Foundation Trust',
        'Kettering General Hospital NHS Foundation Trust',
        'King`s College Hospital NHS Foundation Trust',
        'Kingston Hospital NHS Foundation Trust',
        'Lancashire Teaching Hospitals NHS Foundation Trust',
        'Leeds Teaching Hospitals NHS Trust',
        'Lewisham and Greenwich NHS Trust',
        'Liverpool Heart and Chest Hospital NHS Foundation Trust',
        'Liverpool University Hospitals NHS Foundation Trust',
        'London North West University Healthcare NHS Trust',
        'Maidstone and Tunbridge Wells NHS Trust',
        'Manchester University NHS Foundation Trust',
        'Medway NHS Foundation Trust',
        'Mid and South Essex NHS Foundation Trust',
        'Mid Cheshire Hospitals NHS Foundation Trust',
        'Mid Essex Hospital Services NHS Trust',
        'Mid Yorkshire Hospitals NHS Trust',
        'Milton Keynes University Hospital NHS Foundation Trust',
        'Moorfields Eye Hospital NHS Foundation Trust',
        'Norfolk and Norwich University Hospitals NHS Foundation Trust',
        'North Bristol NHS Trust',
        'North Middlesex University Hospital NHS Trust',
        'North Tees and Hartlepool NHS Foundation Trust',
        'North West Anglia NHS Foundation Trust',
        'Northampton General Hospital NHS Trust',
        'Northern Devon Healthcare NHS Trust',
        'Northern Lincolnshire and Goole NHS Foundation Trust',
        'Northumbria Healthcare NHS Foundation Trust',
        'Nottingham University Hospitals NHS Trust',
        'Oxford University Hospitals NHS Foundation Trust',
        'Pennine Acute Hospitals NHS Trust',
        'Poole Hospital NHS Foundation Trust',
        'Portsmouth Hospitals NHS Trust',
        'Queen Victoria Hospital NHS Foundation Trust',
        'Royal Berkshire NHS Foundation Trust',
        'Royal Brompton &amp; Harefield NHS Foundation Trust',
        'Royal Cornwall Hospitals NHS Trust',
        'Royal Devon and Exeter NHS Foundation Trust',
        'Royal Free London NHS Foundation Trust',
        'Royal National Orthopaedic Hospital NHS Trust',
        'Royal Papworth Hospital NHS Foundation Trust',
        'Royal Surrey County Hospital NHS Foundation Trust',
        'Royal United Hospitals Bath NHS Foundation Trust',
        'Salford Royal NHS Foundation Trust',
        'Salisbury NHS Foundation Trust',
        'Sandwell and West Birmingham Hospitals NHS Trust',
        'Sheffield Teaching Hospitals NHS Foundation Trust',
        'Sherwood Forest Hospitals NHS Foundation Trust',
        'Shrewsbury and Telford Hospital NHS Trust',
        'South Tees Hospitals NHS Foundation Trust',
        'South Tyneside and Sunderland NHS Foundation Trust',
        'South Warwickshire NHS Foundation Trust',
        'Southport and Ormskirk Hospital NHS Trust',
        'St George`s University Hospitals NHS Foundation Trust',
        'St Helens and Knowsley Teaching Hospitals NHS Trust',
        'Stockport NHS Foundation Trust',
        'Surrey and Sussex Healthcare NHS Trust',
        'Tameside and Glossop Integrated Care NHS Foundation Trust',
        'Taunton and Somerset NHS Foundation Trust',
        'The Christie NHS Foundation Trust',
        'The Clatterbridge Cancer Centre NHS Foundation Trust',
        'The Dudley Group NHS Foundation Trust',
        'The Hillingdon Hospitals NHS Foundation Trust',
        'The Newcastle Upon Tyne Hospitals NHS Foundation Trust',
        'The Princess Alexandra Hospital NHS Trust',
        'The Queen Elizabeth Hospital, King`s Lynn, NHS Foundation Trust',
        'The Robert Jones and Agnes Hunt Orthopaedic Hospital NHS Foundation Trust',
        'The Rotherham NHS Foundation Trust',
        'The Royal Bournemouth and Christchurch Hospitals NHS Foundation Trust',
        'The Royal Marsden NHS Foundation Trust',
        'The Royal Orthopaedic Hospital NHS Foundation Trust',
        'The Royal Wolverhampton NHS Trust',
        'The Walton Centre NHS Foundation Trust',
        'Torbay and South Devon NHS Foundation Trust',
        'United Lincolnshire Hospitals NHS Trust',
        'University College London Hospitals NHS Foundation Trust',
        'University Hospital Southampton NHS Foundation Trust',
        'University Hospitals Birmingham NHS Foundation Trust',
        'University Hospitals Bristol and Weston NHS Foundation Trust',
        'University Hospitals Coventry and Warwickshire NHS Trust',
        'University Hospitals of Derby and Burton NHS Foundation Trust',
        'University Hospitals of Leicester NHS Trust',
        'University Hospitals of Morecambe Bay NHS Foundation Trust',
        'University Hospitals of North Midlands NHS Trust',
        'University Hospitals Plymouth NHS Trust',
        'Walsall Healthcare NHS Trust',
        'Warrington and Halton Teaching Hospitals NHS Foundation Trust',
        'West Hertfordshire Hospitals NHS Trust',
        'West Suffolk NHS Foundation Trust',
        'Weston Area Health NHS Trust',
        'Whittington Health NHS Trust',
        'Wirral University Teaching Hospital NHS Foundation Trust',
        'Worcestershire Acute Hospitals NHS Trust',
        'Wrightington, Wigan and Leigh NHS Foundation Trust',
        'Wye Valley NHS Trust',
        'Yeovil District Hospital NHS Foundation Trust',
        'York Teaching Hospital NHS Foundation Trust',
    ],

    datasets: [
        {
          label: 'Average Length of Stay Benchmatked - Open',
          backgroundColor: '#a47eaa',
          data: [
            2.40, 2.39, 2.38, 2.37, 2.36, 2.35, 2.34, 2.33, 2.31, 2.30, 
            2.29, 2.28, 2.27, 2.26, 2.25, 2.24, 2.23, 2.22, 2.21, 2.20, 
            2.19, 2.18, 2.17, 2.16, 2.15, 2.14, 2.13, 2.12, 2.11, 2.10, 
            2.09, 2.08, 2.07, 2.06, 2.05, 2.04, 2.03, 2.02, 2.01, 2.00, 
            1.99, 1.98, 1.97, 1.96, 1.95, 1.94, 1.93, 1.92, 1.91, 1.90, 
            1.89, 1.88, 1.87, 1.86, 1.85, 1.84, 1.83, 1.82, 1.81, 1.80, 
            1.79, 1.78, 1.77, 1.76, 1.75, 1.74, 1.73, 1.72, 1.71, 1.70, 
            1.69, 1.68, 1.67, 1.66, 1.65, 1.64, 1.63, 1.62, 1.61, 1.60, 
            1.59, 1.58, 1.57, 1.56, 1.55, 1.54, 1.53, 1.52, 1.51, 1.50, 
            1.49, 1.48, 1.47, 1.46, 1.45, 1.44, 1.43, 1.42, 1.41, 1.40, 
            1.39, 1.38, 1.37, 1.36, 1.35, 1.34, 1.33, 1.32, 1.31, 1.30, 
            1.29, 1.28, 1.27, 1.26, 1.25, 1.24, 1.23, 1.22, 1.21, 1.20, 
            1.19, 1.18, 1.17, 1.16, 1.15, 1.14, 1.13, 1.12, 1.11, 1.10, 
            1.09, 1.08, 1.07, 1.06, 1.05, 1.04, 1.03, 1.02, 1.01, 1.00
        ]
    }
]
}
export const options = {
    responsive: true,
    maintainAspectRatio: false,
    interaction: {
        // mode: 'index',
        intersect: false,
    },
    plugins: {
        // title: {
        //     display: true,
        //     text: 'Emergency SOS, Coded Sepsis & Emergency Admissions',
        //     font: {
        //         size: 14,
        //         weight: 'bold'
        //     }
        // },
        // subtitle: {
        //     display: true,
        //     text: 'Custom Chart Subtitle',
        //     font: {
        //         size: 14,
        //         weight: 'bold'
        //     }
        // },
        legend: {
            display: true,
            position: 'top',
            align: 'center',
            labels: {
                color: ['#000000'],
                useBorderRadius: true,
                borderRadius: 2,
                boxWidth: 10,
                boxHeight: 10,
                // padding: 10,
                font: {
                    size: 11,
                    // weight: 'bold'
                }
            },
            title: {
                display: false,
                padding: 0,
                color: '#0000ff',
                text: 'Legend Title',
            }
        }
    },
    scales: {
        x: {
            // stacked: true,
            grid: {
                drawOnChartArea: false, // only want the grid lines for one axis to show up
            },
            ticks: {
                display: false,
                font: {
                    size: 11,
                    weight: 'normal'
                },
                minRotation: 0 // Roptate the label
            }
        },
    },
} 